# Generated by Django 4.2.2 on 2024-02-03 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0002_authordetailsapiinfo_alter_content_unique_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='avatar_url',
            field=models.URLField(null=True),
        ),
        migrations.DeleteModel(
            name='AuthorAvatarURL',
        ),
    ]
