version: "3.8"
   
services:
    db:
        image: postgres
        container_name: zelf_postgres
        ports:
          - 5432:5432
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        volumes:
            - pgdata:/var/lib/postgresql/data/
    redis:
        image: "redis:alpine"
        container_name: zelf_redis
        ports:
          - 6379:6379

