version: "3.8"
   
services:
    # db:
    #     image: postgres
    #     container_name: zelf_postgres
    #     ports:
    #       - 5432:5432
    #     environment:
    #         - POSTGRES_DB=postgres
    #         - POSTGRES_USER=postgres
    #         - POSTGRES_PASSWORD=postgres
    #     volumes:
    #         - ./dbdata/db:/var/lib/postgresql/data/
    redis:
        image: "redis:alpine"
        container_name: zelf_redis
        ports:
          - 6379:6379
    esearch:
      container_name: zelf_es
      image: elasticsearch:7.14.2
      environment:
        - discovery.type=single-node
      ports:
        - 9200:9200


# version: "3.8"
   
# services:
#     django:
#         build: .
#         container_name: django
#         command: python manage.py runserver 0.0.0.0:8000
#         volumes:
#             - .:/usr/src/app/
#         ports:
#             - "8000:8000"
#         environment:
#             - DEBUG=1
#             - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
#             - CELERY_BROKER=redis://redis:6379/0
#             - CELERY_BACKEND=redis://redis:6379/0
#         depends_on:
#             - pgdb
#             - redis
#     celery:
#         build: .
#         command: celery -A core worker -l INFO
#         volumes:
#             - .:/usr/src/app
#         environment:
#             - DEBUG=1
#             - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
#             - CELERY_BROKER=redis://redis:6379/0
#             - CELERY_BACKEND=redis://redis:6379/0
#         depends_on:
#             - django
#             - redis
#     pgdb:
#         image: postgres
#         container_name: pgdb
#         environment:
#             - POSTGRES_DB=postgres
#             - POSTGRES_USER=postgres
#             - POSTGRES_PASSWORD=postgres
#         volumes:
#             - pgdata:/var/lib/postgresql/data/
#     redis:
#         image: "redis:alpine"
        
